//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursach5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> UsedSubject { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string IsCompleted { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
